#!/bin/sh

set -e

mkdir -p /tmp/artifacts
go test -timeout 30s ./...

set +e

go test -coverprofile=/tmp/artifacts/go-code-cover -timeout 30s github.com/suzuito/common-herror && go tool cover -html=/tmp/artifacts/go-code-cover -o /tmp/artifacts/go-code-cover.html